# Generated by Django 6.0.4 on 2026-04-22 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('forex', 'Forex')], max_length=20)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='assets_pric_asset_i_bf4c89_idx')],
            },
        ),
    ]
